apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  params:
    - name: action
      description: Action for npm
      default: start
      type: string
    - name: pathContext
      description: Path to application inside git
      default: ""
      type: string
  resources:
    inputs:
      - name: repo
        type: git
        targetPath: code
  steps:
    - name: npm
      image: node:14
      command:
        - /bin/bash
      args: ['-c', 'cd code/$(params.pathContext) && npm install && npm $(params.action)']
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  resources:
    - name: git-repo
      type: git
    - name: final-image
      type: image
  tasks:
    - name: lint
      taskRef:
        name: npm
      params:
        - name: action
          value: run lint
        - name: pathContext
          value: app
      resources:
        inputs:
          - name: repo
            resource: git-repo
    - name: test
      taskRef:
        name: npm
      params:
        - name: action
          value: run test
        - name: pathContext
          value: app
      resources:
        inputs:
          - name: repo
            resource: git-repo
