apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: build-sources
      image: ubuntu
      command:
        - /bin/bash
      args: ['-c', 'echo hello world']